"use client";

import { useEffect, useRef, useState } from "react";
import { Panel, PanelHeader, PanelBody } from "@/components/ui/panel";
import { Tag } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Banner } from "@/components/ui/misc";
import { Modal } from "@/components/ui/modal";
import { Field, Textarea } from "@/components/ui/field";
import { IconCheck, IconLock, IconRefresh, IconTrash, IconWarn } from "@/components/ui/icons";
import { useToast } from "@/components/ui/toast";
import { useActions, useAppState } from "@/lib/store";
import { dateTimeStamp } from "@/lib/format";
import { NOTE_SECTIONS, type NoteSectionKey, type Visit } from "@/lib/types";
import { cx } from "@/lib/cx";

export function NotePanel({
  visit,
  onHoverSection,
}: {
  visit: Visit;
  onHoverSection: (s: NoteSectionKey | null) => void;
}) {
  const state = useAppState();
  const actions = useActions();
  const toast = useToast();
  const note = state.notes[visit.id];
  const tags = state.tags[visit.id] ?? [];
  const addenda = state.addenda[visit.id] ?? [];
  const provenance = state.provenance[visit.id];
  const signedBy = note?.signedBy
    ? state.users.find((u) => u.id === note.signedBy)
    : undefined;

  const [confirmDiscard, setConfirmDiscard] = useState(false);
  const [confirmRegen, setConfirmRegen] = useState(false);
  const [addendumOpen, setAddendumOpen] = useState(false);
  const [addBody, setAddBody] = useState("");
  const [addReason, setAddReason] = useState("");

  if (!note) {
    if (visit.state === "processing") {
      return (
        <Panel>
          <PanelHeader title="Draft case sheet" meta="writing…" />
          <PanelBody>
            <div className="space-y-3 animate-pulse" aria-hidden>
              {[0.9, 0.65, 0.8, 0.5].map((w, i) => (
                <div
                  key={i}
                  className="h-3.5 rounded bg-tint-mist"
                  style={{ width: `${w * 100}%` }}
                />
              ))}
            </div>
          </PanelBody>
        </Panel>
      );
    }
    return null;
  }

  const signed = note.state === "signed";
  const isManual = note.modelUsed === "manual";

  return (
    <Panel id="note">
      <PanelHeader
        title={signed ? "Case sheet" : "Draft case sheet"}
        meta={
          signed ? (
            <span className="inline-flex items-center gap-1.5 text-petrol">
              <IconLock size={12} /> signed · locked
            </span>
          ) : isManual ? (
            "manual note"
          ) : (
            "ready for your review"
          )
        }
      >
        {!signed && !isManual && (
          <div className="ml-3 flex gap-1">
            <button
              type="button"
              onClick={() => setConfirmRegen(true)}
              className="p-1.5 text-muted hover:text-ink hover:bg-tint-mist rounded-[6px]"
              title="Regenerate from the transcript (discards edits)"
            >
              <IconRefresh size={14} />
            </button>
            <button
              type="button"
              onClick={() => setConfirmDiscard(true)}
              className="p-1.5 text-muted hover:text-ink hover:bg-tint-mist rounded-[6px]"
              title="Discard draft, keep transcript"
            >
              <IconTrash size={14} />
            </button>
          </div>
        )}
      </PanelHeader>
      <PanelBody className="pt-2.5">
        {NOTE_SECTIONS.map(({ key, label }) => (
          <NoteSection
            key={key}
            visitId={visit.id}
            section={key}
            label={label}
            value={note.sections[key]}
            lowConfidence={note.confidenceFlags[key] === "low"}
            signed={signed}
            hasProvenance={!!provenance?.[key]?.length}
            onHover={onHoverSection}
            updatedAt={note.updatedAt}
          />
        ))}

        {tags.length > 0 && (
          <div className="pt-3.5">
            <div className="t-label mb-2">
              Extracted tags{" "}
              <span className="normal-case tracking-normal">
                · coded where possible, amber = uncoded
              </span>
            </div>
            <div className="flex flex-wrap gap-1.5">
              {tags.map((t) => (
                <Tag key={t.id} label={t.label} code={t.code} />
              ))}
            </div>
          </div>
        )}

        {signed && (
          <div className="mt-4 pt-3.5 border-t border-line">
            <div className="t-mono-sm text-muted leading-relaxed">
              Signed by {signedBy?.fullName ?? "unknown"} ·{" "}
              {note.signedAt ? dateTimeStamp(note.signedAt) : ""} · content hash{" "}
              {note.contentHash} · {isManual ? "written manually" : `generated by ${note.modelUsed} (${note.promptVersion})`}
            </div>
            {addenda.map((a) => (
              <div
                key={a.id}
                className="mt-3 border border-line rounded-field p-3.5 bg-soft"
              >
                <div className="t-label mb-1">
                  Addendum · {dateTimeStamp(a.createdAt)} ·{" "}
                  {state.users.find((u) => u.id === a.authorId)?.fullName}
                </div>
                <p className="text-[14px] m-0">{a.body}</p>
                <p className="t-mono-sm text-muted mt-1.5 mb-0">
                  reason: {a.reason}
                </p>
              </div>
            ))}
            <Button
              size="sm"
              variant="ghost"
              className="mt-3"
              onClick={() => setAddendumOpen(true)}
            >
              Add an addendum
            </Button>
          </div>
        )}
      </PanelBody>

      {/* discard: the §2.4 counter-metric, logged as such */}
      <Modal
        open={confirmDiscard}
        onClose={() => setConfirmDiscard(false)}
        eyebrow="Discard draft"
        title="Keep the transcript, drop the draft?"
      >
        <p className="text-[13.5px] text-muted leading-relaxed mb-4">
          The draft goes; the transcript stays for reference and you write
          freehand. Discards are tracked, because if drafts keep getting thrown away,
          that's a note-quality problem we need to see.
        </p>
        <div className="flex justify-end gap-2.5">
          <Button onClick={() => setConfirmDiscard(false)}>Keep draft</Button>
          <Button
            variant="primary"
            onClick={() => {
              actions.discardDraft(visit.id);
              setConfirmDiscard(false);
              toast("Draft discarded, transcript kept", "info");
            }}
          >
            Discard draft
          </Button>
        </div>
      </Modal>

      <Modal
        open={confirmRegen}
        onClose={() => setConfirmRegen(false)}
        eyebrow="Regenerate"
        title="Re-draft from the transcript?"
      >
        <p className="text-[13.5px] text-muted leading-relaxed mb-4">
          A fresh draft is written from the final transcript. Your edits to
          the current draft are discarded.
        </p>
        <div className="flex justify-end gap-2.5">
          <Button onClick={() => setConfirmRegen(false)}>Cancel</Button>
          <Button
            variant="primary"
            onClick={() => {
              actions.regenerateNote(visit.id);
              setConfirmRegen(false);
            }}
          >
            <IconRefresh size={14} /> Regenerate
          </Button>
        </div>
      </Modal>

      {/* addendum: the only way to change a signed note (FR-NOTE-9) */}
      <Modal
        open={addendumOpen}
        onClose={() => setAddendumOpen(false)}
        eyebrow="Signed notes are immutable"
        title="Append an addendum"
      >
        <div className="space-y-3.5">
          <Field label="Addendum">
            <Textarea
              value={addBody}
              onChange={(e) => setAddBody(e.target.value)}
              placeholder="What needs to be added or corrected"
              rows={3}
            />
          </Field>
          <Field label="Reason">
            <Textarea
              value={addReason}
              onChange={(e) => setAddReason(e.target.value)}
              placeholder="Why the record is being amended"
              rows={2}
            />
          </Field>
          <div className="flex justify-end gap-2.5">
            <Button onClick={() => setAddendumOpen(false)}>Cancel</Button>
            <Button
              variant="primary"
              disabled={addBody.trim().length < 3 || addReason.trim().length < 3}
              onClick={() => {
                actions.addAddendum(visit.id, addBody.trim(), addReason.trim());
                setAddendumOpen(false);
                setAddBody("");
                setAddReason("");
                toast("Addendum appended with its own timestamp");
              }}
            >
              Append
            </Button>
          </div>
        </div>
      </Modal>
    </Panel>
  );
}

/* ── a single inline-editable section with 800ms autosave ── */

function NoteSection({
  visitId,
  section,
  label,
  value,
  lowConfidence,
  signed,
  hasProvenance,
  onHover,
  updatedAt,
}: {
  visitId: string;
  section: NoteSectionKey;
  label: string;
  value: string;
  lowConfidence: boolean;
  signed: boolean;
  hasProvenance: boolean;
  onHover: (s: NoteSectionKey | null) => void;
  updatedAt: string;
}) {
  const actions = useActions();
  const offline = useAppState().connection === "offline";
  const [local, setLocal] = useState(value);
  const [saveState, setSaveState] = useState<"idle" | "saving" | "saved">("idle");
  const focusedRef = useRef(false);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const taRef = useRef<HTMLTextAreaElement>(null);

  // pull external changes (regenerate) when not editing
  useEffect(() => {
    if (!focusedRef.current) setLocal(value);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value, updatedAt]);

  // autosize
  useEffect(() => {
    const ta = taRef.current;
    if (!ta) return;
    ta.style.height = "0px";
    ta.style.height = `${ta.scrollHeight}px`;
  }, [local]);

  const onChange = (v: string) => {
    setLocal(v);
    setSaveState("saving");
    if (timerRef.current) clearTimeout(timerRef.current);
    timerRef.current = setTimeout(() => {
      actions.editNote(visitId, section, v);
      setSaveState("saved");
      setTimeout(() => setSaveState("idle"), 1600);
    }, 800); // FR-NOTE-2: debounce 800ms
  };

  return (
    <div
      className="py-3 border-b border-dashed border-line last:border-0"
      onMouseEnter={() => hasProvenance && onHover(section)}
      onMouseLeave={() => onHover(null)}
    >
      <div className="flex items-center gap-2 mb-1">
        <span className="t-label">{label}</span>
        {hasProvenance && !signed && (
          <span className="t-mono-sm text-faint normal-case">
            hover to trace source lines
          </span>
        )}
        <span className="ml-auto t-mono-sm text-muted" aria-live="polite">
          {saveState === "saving" && (offline ? "saving locally…" : "saving…")}
          {saveState === "saved" && (
            <span className="inline-flex items-center gap-1 text-sea">
              <IconCheck size={11} /> {offline ? "saved locally" : "saved"}
            </span>
          )}
        </span>
      </div>

      {lowConfidence && !signed && (
        <Banner tone="warn" icon={<IconWarn size={14} />} className="mb-2">
          Audio was unclear here. Please check this section against your own
          memory of the examination.
        </Banner>
      )}

      {signed ? (
        <p className="text-[14.5px] leading-relaxed m-0 whitespace-pre-wrap">
          {value || <span className="text-muted">Not recorded</span>}
        </p>
      ) : (
        <textarea
          ref={taRef}
          value={local}
          onChange={(e) => onChange(e.target.value)}
          onFocus={() => {
            focusedRef.current = true;
            if (hasProvenance) onHover(section);
          }}
          onBlur={() => {
            focusedRef.current = false;
            onHover(null);
          }}
          rows={1}
          placeholder="Not recorded"
          aria-label={label}
          className={cx(
            "w-full resize-none overflow-hidden text-[14.5px] leading-relaxed bg-transparent",
            "border border-transparent rounded-[8px] px-2 py-1.5 -mx-2",
            "hover:border-line hover:bg-soft focus:outline-none focus:border-sea focus:bg-chalk focus:ring-[3px] focus:ring-sea/15 transition-colors",
          )}
        />
      )}
    </div>
  );
}
